# Use docker image ical/source with lot's of develop library already builtin.
image:
  name: ical/source:latest
  entrypoint: ["/bin/bash"]

before_script:
  - git submodule update --init

variables:
  # Submodule behavier, reference to:
  # http://140.127.205.188/help/ci/yaml/README#git-submodule-strategy
  # We should add 'git submodule update --init' in 'before_script' or CI may fail
  #GIT_SUBMODULE_STRATEGY: normal
  # Do a shallow clone, reference to:
  # http://140.127.205.188/help/ci/yaml/README#shallow-cloning
  GIT_DEPTH: "3"

# Build task
build:
  stage: build

  # Run build
  script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON -DBUILD_HG_MONITOR=OFF
    - make install

  # Keep built binaries (expire in 1 day)
  artifacts:
    paths:
      - build/
    expire_in: 1 day

# Test task
test:
  stage: test

  # Run test
  script:
    - ./build/install/bin/test_lib_link

# vim: set tabstop=2 shiftwidth=2 expandtab :
